name: Continuous Integration


on:
  push:
    branches: ["**"]

jobs:
  ci:
    name: CI Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"  

      - name: Install dependencies
        run: npm install       

      - name: Run ESLint
        run: npx eslint . --fix

      - name: Run tests
        run: npm test          
